### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by aoy12** [OriHoch/django-oscar-demo#1]
Hey Ori, 
Thank you for your project. It's helping me quite a bit for my own start-up. 

I just would like to say that I think in the settings.py file we still need to define the  email settings like the email_host, -_TLS, -_SSL etc and all the other variables to make use of OSCAR's email send out for say signup. Is that true? Am I on the right track here? 

Sorry, I am a django-python newbie 

Cheers,
Omar

**Comment by OriHoch** [comment]
yes, sounds right
